// Create a simple express backend with three routes
// routes are /roast, /pun, /random
// each route returns a random roast, pun
const puns = [
    `#1 Which Country’s capital has the fastest-growing population? Ireland. Every day it’s Dublin.`,
    `#2 Yesterday a clown held the door open for me. It was such a nice jester.`,
    `#3 I was going to make myself a belt made out of watches but then I realized it would be a waist of time.`,
    `#4 I asked my French friend if she likes to play video games. She said "Wii".`,
    `#5 The machine at the coin factory just suddenly stopped working with no explanation. It doesn’t make any cents.`,
    `#6 Did you hear about the auto body shop that just opened? It comes highly wreck-a-mended.`,
    `#7 What’s the difference between a hippo and a Zippo? A hippo is really heavy and a Zippo is a little lighter.`,
    `#8 All these sea monster jokes are just Kraken me up.`,
    `#9 Why can’t you run through a campground? You can only ran because it’s past tents.`,
    `#10 What do dogs study for their PhDs? A Barkeology.`,
    `#11 What do you call a bee that can’t make up its mind? A Maybe.`,
    `#12 What’s the difference between a dog and a marine biologist? One wags a tail and the other tags a whale.`,
    `#13 What did the watermelon say to the cantaloupe? You’re one in a melon.`,
    `#14 Don’t go bacon my heart. I couldn’t if I fried.`,
    `#15 If you were a fruit you’d be a fine-apple.`,
    `#16 I love you from my head tomatoes.`,
    `#17 What do you get when two dinosaurs crash their cars? A T-Rex.`,
    `#18 What job did the frog have at the hotel? A Bellhop.`,
    `#19 What do you call a pig that does karate? Pork chop.`,
    `#20 What do you call an everyday potato? A commentator.`,
    `#21 How do you put a baby alien to sleep? You rocket.`,
    `#22 What do you call a thieving crocodile? A crookodile.`,
    `#23 What do you call a lazy kangaroo? A pouch potato.`,
    `#24 What did the volcano say to his wife? I lava you.`,
    `#25 What do you call and owl that does magic tricks? A Hoodini.`,
    `#26 Why did the banana go to the doctor? It wasn’t peeling well.`,
    `#27 What do you call a classy fish? Sofishticated.`,
    `#28 Are you a cheetah? No you lion.`,
    `#29 How do you organize a space party? You planet.`,
    `#30 Why did the bicycle fall over? because it was two tired. - @FloralNona `,
    `#31 Shout out to the people who ask what the opposite of in is.`,
    `#32 I’m only friends with 25 letters of the alphabet. I don’t know Y.`,
    `#33 What sound does a sleeping T-Rex make? A dino-snore.`,
    `#34 Two windmills are standing in a wind farm. One asks "What’s your favorite kind of music?" The other says "I’m a big metal fan".`,
    `#35 Want to hear something terrible? Paper. See? I told you it was tear-able.`,
    `#36 Last night I dreamed I was swimming in an ocean of orange soda. But it was just a Fanta sea.`,
    `#37 A man sued an airline company after it lost his luggage. Sadly he lost his case.`,
    `#38 Atoms are untrustworthy little critters. They make up everything.`,
    `#39 The past the present and the future walk into a bar it was tense.`,
    `#40 An atom loses an electron it says "Man I really gotta keep an ion them".`,
    `#41 Did you hear about the man who was accidentally buried alive?  It was a grave mistake.`,
    `#42 I had to clean out my spice rack and found everything was too old and had to be thrown out.  What a waste of thyme.`,
    `#43I hate how funerals are always at 9 a.m. I’m not really a mourning person.`,
    `#44I lost my job at the bank on my very first day. A woman asked me to check her balance so I pushed her over.`,
    `#45 Ray’s friends claim he’s a baseball nut. He says "they’re way off base".`,
    `#46 Why not go out on a limb? Isn’t that where all the fruit is.`,
    `#47 My ex used to hit me with stringed instruments. If only I had known about her history of violins.`,
    `#48 I met this girl at a vegan shop after that I never met herbivore. - @B3ard3dH0bbits `,
    `#49 Did you know the guy that invented the door knocker won a No bell prize. - @sickwiy `,
    `#50 What do you call a bear with no teeth? Gummybear.`,
    `#51 What do you call a spellcaster pig in the desert? A ham sand witch. - @CaydenPlays21 `,
    `#52 What do you call a dog that’s ready for spring break? Pug boat.`,
    `#53 What do you call a sad pup? Mellon collie.`,
    `#54 What was the dogs favorite type of homework to do? A lab report.`,
    `#55 What did the dog say to his doctor? "Be careful with the thermometer last time it was a bit ruff".`,
    `#56 I’m looking for the man who shot my paw.`,
    `#57 What do you call a dog who does magic tricks? A Labracadabrador.`,
    `#58 What did the dog in the hard hat say? My specialty is roofing.`,
    `#59 What do you call a dog magician? A Labrabacadabrador.`,
    `#60 My buddy said he threw a stick five miles and his dog managed to find it and brought it back. Seems a little far fetched.`,
    `#61 Guess what I’ll call my house key? My Corg-key.`,
    `#62 The dog had a ruff day.`,
    `#63 Don’t stop retreievin’ hold on to that feline.`,
    `#64 I’m not fat. I’m just a little husky.`,
    `#65 I need to see a dentist. One of my canines is getting loose.`,
    `#66 Did you hear about the dog that gave birth on the side of the road? She was ticketed for littering.`,
    `#67 What breed of dog tells off-color jokes? A smutt.`,
    `#68 Which dog breed chases anything that’s red? A bull dog.`,
    `#69 Don't have phone sex. You might get hearing aids.`,
    `#70 What do you do when a dog eats your English homework? Take the words right out of its mouth.`,
    `#71 What do you get when you cross a cocker spaniel a poodle and a rooster? A cockerpoodledoo.`,
    `#72 Why did the tree think the dog was talking to him? He kept saying "bark bark bark".`,
    `#73 Why aren’t dogs good dancers? Because they have two left feet.`,
    `#74 What kind of dog does Dracula have? A bloodhound.`,
    `#75 What did the Dalmatian say after he had some kibble? That hit the spot.`,
    `#76 What’s a dog’s favorite late-night TV host? Canine O’Brien.`,
    `#77 What’s a chihuahua’s favorite Christmas carol? Fleas Navidad.`,
    `#78 I wanted to see a bunch of different animals at the zoo but all they had was one small dog. It was a shih-tzu.`,
    `#79 My buddy said he threw a stick 20 miles but his dog still found it and retrieved it. I dunno sounds a little far fetched to me.`,
    `#80 I wanted to see a bunch of different animals at the zoo but all they had was one small dog. It was a shih-tzu.`,
    `#81 Why can't Harry Potter tell the difference between the pot he uses to make potions and his best friends? They're both cauld ron.`,
    `#82 My boss yelled at me the other day. "You’ve got to be the worst train driver in history. How many trains did you derail last
    year?" I said "Can’t say for sure it’s so hard to keep track".`,
    `#83 6:30 is the best time on a clock hands down.`,
    `#84 What year will be the year all eye doctors go out of buisness? 2020. - @joshua333333 `,
    `#85 What do you call a thieving alligator? A Crookodile.`,
    `#86 What do you call a pig that does karate? Pork chop.`,
    `#87 How do you throw a space party? You planet.`,
    `#88 How was Rome split in two? With a pair of Ceasars.`,
    `#89 Nope. Unintended.`,
    `#90 The shovel was a ground breaking invention. But everyone was blow away by the leaf blower.`,
    `#91 A scarecrow says, "This job isn't for everyone. But hay it's in my jeans".`,
    `#92 A Buddhist walks up to a hot dog stand and says "Make me one with everything".`,
    `#93 Did you hear about the guy who lost the left side of his body? He's alright now.`,
    `#94 What do you call a girl with one leg that's shorter than the other? Ilene.`,
    `#95 The broom swept the nation away.`,
    `#96 I did a theatrical performance on puns. It was a play on words.`,
    `#97 What does a clock do when it's hungry? It goes back for seconds.`,
    `#98 What do you do with a dead chemist? You barium.`,
    `#99 I bet the person who created the door knocker won a Nobel prize.`,
    `#101 Well you got Pun 100! Next Pun will be the greatest you've heard yet.`,
    `#102 Towels can’t tell jokes. They have a dry sense of humor.`,
    `#103 Two birds are sitting on a perch and one says “Do you smell fish”?`,
    `#104 Did you hear about the cheese factory that exploded in france? There was nothing but des brie.`,
    `#105 Do you know sign language? You should learn it. It’s pretty handy.`,
    `#106 What do you call a beautiful pumpkin? GOURDgeous.`,
    `#107 Why did one banana spy on the other? Because she was appealing.`,
    `#108 What do you call a cow with no legs? Ground beef.`,
    `#109 What do you call a cow with two legs? Lean beef.`,
    `#110 What do you call a cow with all of its legs? High steaks.`,
    `#111 A cross eyed teacher couldn’t control his pupils.`,
    `#112 After the accident the juggler didn’t have the balls to do it.`,
    `#113 I used to be afraid of hurdles but I got over it`,
    `#114 To write with a broken pencil is pointless.`,
    `#115 I read a book on anti-gravity. I couldn’t put it down.`,
    `#116 I couldn’t remember how to throw a boomerang but it came back to me.`,
    `#117 What did the buffalo say to his son? Bison.`,
    `#118 What should you do if you’re cold? Stand in the corner. It’s 90 degrees.`,
    `#119 How does Moses make coffee? Hebrews it.`,
    `#120 The energizer bunny went to jail. He was charged with battery.`,
    `#121 What did the alien say to the pitcher of water? Take me to your liter.`,
    `#122 What happens when you eat too many spaghetti-o's? You have a vowel movement.`,
    `#123 The soldier who survived mustard gas and pepper spray was a seasoned veteran.`,
    `#124 Sausage puns are the wurst.`,
    `#125 What do you call a bear with no teeth? A gummy bear.`,
    `#126 How did Darth Vader know what Luke was getting him for his birthday? He could sense his presence.`,
    `#127 Why shouldn’t you trust atoms? They make up everything.`,
    `#128 What’s the difference between a bench a fish and a bucket of glue? You can’t tune a bench but you can tuna fish. I bet you got stuck on the bucket of glue part.`,
    `#129 What’s it called when you have too many aliens? Extraterrestrials.`,
    `#130 Want to hear a pizza joke? Never mind it’s too cheesy.`,
    `#131 What do you call a fake noodle? An impasta.`,
    `#132 What do cows tell each other at bedtime? Dairy tales.`,
    `#133 Why can’t you take inventory in Afghanistan? Because of the tally ban.`,
    `#134 Why didn’t the lion win the race? Because he was racing a cheetah.`,
    `#135 Why did the man dig a hole in his neighbor’s backyard and fill it with water? Because he meant well.`,
    `#136 What happens to nitrogen when the sun comes up? It becomes daytrogen.`,
    `#137 What’s it called when you put a cow in an elevator? Raising the steaks.`,
    `#138 Why did the tomato turn red? Because it saw the salad dressing.`,
    `#139 What kind of car does a sheep drive? A Lamborghini. But if that breaks down they drive their SuBAHHru.`,
    `#140 What do you call a Spanish pig? Porque.`,
    `#141 What do you call a line of rabbits marching backwards? A receding hairline.`,
    `#142 Why don’t vampires go to barbecues? They don’t like steak.`,
    `#143 A cabbage and celery walk into a bar and the cabbage gets served first because he was a head.`,
    `#144 How do trees access the internet? They log on.`,
    `#145 Why should you never trust a train? They have loco motives.`,
    `#146 I’m reading a book about anti-gravity. It’s impossible to put down.`,
    `#147 How did the picture end up in jail? It was framed.`,
    `#148 My ex-wife still misses me. But her aim is starting to improve.`, 
    `#149 I used to go fishing with Skrillex. But he kept dropping the bass.`,
    `#150 Sure I can drink brake fluid. But I can stop anytime.`,
    `#151 What's the difference between a well dressed man on a unicycle and a sloppily dressed one on a bike? Attire. - @ryuugajoh `,
    `#152 If you see a robbery at an Apple store. Does that make you an iWitness? - @FreeClancyBucks `,
    `#153 Why was King Arthur's army too tired to fight? It had too many sleepless knights. - @FreeClancyBucks `,
    `#154 I wa#sn't originally going to get a brain transplant but then I changed my mind.`,
    `#155 Yest#erday I accidentally swallowed some food coloring. The doctor says I'm OK but I feel like I've dyed a little inside.`,
    `#156 My girlfriend thought I’d never be able to make a car out of spaghetti. You should’ve seen her face when I drove pasta!`,
    `#157 Coffee has a rough time in our house. It gets mugged every single morning!`,
    `#158 I just found out that I’m color blind. The news came completely out of the green!`,
    `#159 What do you call the wife of a hippie? A Mississippi!`,
    `#160 Whenever I undress in the bathroom. My shower gets turned on!`,
    `#161 I was walking through a quarry. I said to the foreman “That sure is a big rock!” “Boulder” he corrected me. So I stuck out my chest and shouted “THAT SURE IS A BIG ROCK!!”`,
    `#162 My parents said I can’t drink coffee anymore. Or else they’ll ground me!`,
    `#163 Why didn’t the cat go to the vet? He was feline fine!`,
    `#164 What should a lawyer always wear to a court? A good lawsuit!`,
    `#165 Somebody stole all my lamps. ...and I couldn’t be more de-lighted!`,
    `#166 My wife refuses to go to a nude beach with me... I think she’s just being clothes-minded!`,
    `#167 The quickest way to make antifreeze. Just steal her blanket!`,
    `#168 Did you hear about that cheese factory that exploded in France? There was nothing left but de Brie!`,
    `#169 What do you do with chemists when they die? Barium!`,
    `#170 Three conspiracy theorists walk into a bar... You can’t tell me that’s just a coincidence!`,
    `#171 Never date someone cross-eyed... You’ll always catch them seeing other people on the side!`,
    `#172 What did the mayonnaise say when somebody opened the refrigerator? “Hey close the door! I’m dressing!”`,
    `#173 Time flies like an arrow... Fruit flies like a banana!`,
    `#174 How do you make a good egg-roll? You push it down a hill!`,
    `#175 Apple is designing a new automatic car. But they’re having trouble installing Windows!`,
    `#176 That baseball player was such a bad sport. He stole third base and then just went home!`,
    `#177 I’ve started sleeping in our fireplace. Now I sleep like a log!`,
    `#178 I have a few jokes about unemployed people... But none of them work!`,
    `#179 Every soccer player’s favorite beverage? Penal-tea!`,
    `#180 Did you hear about the kidnapping at school? It’s okay. He woke up!`,
    `#181 What do you call an overweight psychic? A four-chin teller!`,
    `#182 I used to wonder why Frisbees looked bigger the closer they came... And then it hit me!`,
    `#183 Two egotists started a fight. It was an I for an I!`,
    `#184 I’m glad I know sign language. It can come in pretty handy!`,
    `#186 A police officer just knocked on my door and told me my dogs are chasing people on bikes. That’s ridiculous. My dogs don’t even own bikes!`,
    `#187 I wanted to take pictures of the fog this morning... But I mist my chance. I guess I could dew it tomorrow!`,
    `#188 Why did the scientist install a knocker on his front door? He wanted to win the No-bell prize!`,
    `#189 My dad unfortunately passed away when we couldn’t remember his blood type... His last words to us were “Be positive!”`,
    `#190 Did you hear about the guy who had his left leg and left arm amputated after a car crash? He’s all right now!`,
    `#191 I became a vegetarian. Huge missed-steak!`,
    `#192 What should you call an average potato? A commen-tator!`,
    `#193 I bought some shoes on the drug black market... I don’t know what they’re laced with but I’ve been tripping all day!`,
    `#194 Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink!`,
    `#195 I saw an ad for burial plots, and I thought... “That’s the last thing I need!”`,
    `#196 I can’t believe I got fired from the calendar factory. All I did was take a day off!`,
    `#197 If you've been thinking about singing karaoke with a friend just duet!`,
    `#198 I love when candy canes are in mint condition.`,
    `#199 A life in politics is full of parties.`,
    `#200 I wanted to be an astronaut but my parents told me the sky was the limit.`,
    `#201 I didn't like having long nails but they're growing on me.`,
    `#202 Knowing how to pick locks has really opened a lot of doors for me.`,
    `#203 My wife wanted to make a joke about domestic abuse but I beat her to it.`,
    `#204 Man choking on sugar seems like the sweetest way to die!`,
    `#205 Me and my receding hairline? We go way back.`,
    `#206 How many tickles does it take to make an octopus laugh? 10-tickles.`,
    `#207 My leaf blower doesn’t work. It just sucks!`,
    `#208 Need an Ark? I Noah guy.`,
    `#209 How does Moses make coffee? Hebrews it.`,
    `#210 How do turtles communicate with each other? With shell phones.`,
    `#211 I’m positive I just lost an electron. Better keep an ion that.`,
    `#212 How does an attorney sleep? First he lies on one side then he lies on the other.`,
    `#213 What do you call a super articulate dinosaur? A Thesaurus.`,
    `#214 How did the Native Americans get to America first? They had reservations.`,
    `#215 Why was King Arthur’s army too tired to fight? All of those sleepless knights.`,
    `#216 What kind of cats like to go bowling? Alley cats.`,
    `#217 What’s so great about whiteboards? If you think about it they’re pretty re-markable!`,
    `#218 I went to see the Liberty Bell the other day. It’s not all it’s cracked up to be.`,
    `#219 How do you invite a dinosaur for lunch? Tea Rex?`,
    `#220 What do you call someone who tells too many dinosaur jokes? A dino-bore.`,
    `#221 What’s america’s favorite soda? Mini soda.`,
    `#222 I’ve got a phobia of over-engineered buildings. It’s a complex complex complex.`,
    `#223 Napoleon may not have designed the coat he wore… But he did have a hand in it.`,
    `#224 What kind of tea did the American Colonists want? Liberty.`,
    `#225 What do you call a dinosaur with one eye? A do-you-think-he-saur-us.`,
    `#226 Did you hear about the negative nelly who hates German sausage? He always fears the wurst.`,
    `#227 What do you call a goat that acts immaturely? A silly billy.`,
    `#228 Who invented King Arthur’s round table? Sir Cumference.`,
    `#229 Why did the mathematician work from home? Because he could only function in his domain.`,
    `#230 I accidentally went to bed with my contact lenses in the other night. My dreams have never been clearer.`,
    `#231 Is your iPad making you fall asleep? I can help—there’s a nap for that.`,
    `#232 Will glass coffins be a success? Remains to be seen.`,
    `#233 The male pig puts everyone to sleep. You might say he’s quite a boar.`,
    `#234 I like bowling. Seriously it’s right up my alley.`,
    `#235 What do you call a girl with an hourglass figure? A complete waist of time.`,
    `#236 What do you call a goat that’s lazy? Billy Idle.`,
    `#237 I knew a mathematician who couldn’t afford lunch. He could binomial.`,
    `#238 I went to the costume party as a turtle. I had a shell of a time.`,
    `#239 I wanted to learn to drive a stick shift. Thing is... I couldn’t find a manual.`,
    `#240 What did the mermaid wear to math class? An algae-bra.`,
    `#241 Where do robots go for fun? The circuits.`,
    `#242 What do you call a turtle who takes up photography? A snapping turtle.`,
    `#243 What do you call a royal goat wearing denim? Billy Jean King.`,
    `#244 What happened when the semi-colon broke grammar laws? He was given two consecutive sentences.`,
    `#245 Why do math teachers make good dancers? Because they have algorithm.`,
    `#246 Why don't some couples go to the gym? Because some relationships don't work out.`,
    `#247 A friend of mine tried to annoy me with bird puns. But I soon realized that toucan play at that game.`,
    `#248 I'd tell you a chemistry joke but I know I wouldn't get a reaction.`,
    `#249 Have you ever tried to eat a clock? It's very time consuming.`,
    `#250 The man that pointed out the burning building was a fire distinguisher.`,
];



const roasts = [
  `I'd give you a nasty look but you've already got one`,
  `If you were going to be two-faced at least make one of them pretty`,
  `I love what you've done with your hair. How do you get it to come out of the nostrils like that`,
  `If laughter is the best medicine your face must be curing the world`,
  `The only way you'll ever get laid is if you crawl up a chicken's ass and wait`,
  `It looks like your face caught fire and someone tried to put it out with a hammer`,
  `I'd like to see things from your point of view, but I can't seem to get my head that far up your ass`,
  `I've seen people like you before but I had to pay admission`,
  `Scientists say the universe is made up of neutrons protons and electrons. They forgot to mention morons`,
  `You're so fat you could sell shade`,
  `Your lips keep moving but all I hear is Blah blah blah`,
  `Your family tree must be a cactus because everyone on it is a prick`,
  `You'll never be the man your mother is`,
  `I'm sorry, was I meant to be offended? The only thing offending me is your face`,
  `Someday you'll go far... and I hope you stay there`,
  `Which sexual position produces the ugliest children? Ask your mother`,
  `Stupidity's not a crime so you're free to go`,
  `If I had a face like yours I'd sue my parents`,
  `Your doctor called with your colonoscopy results. Good news - they found your head`,
  `No those pants don't make you look fatter - how could they`,
  `Save your breath - you'll need it to blow up your date`,
  `You're not stupid you just have bad luck when thinking`,
  `If you really want to know about mistakes you should ask your parents`,
  `Please keep talking. I always yawn when I am interested`,
  `The zoo called. They're wondering how you got out of your cage`,
  `Whatever kind of look you were going for you missed`,
  `I was hoping for a battle of wits but you appear to be unarmed`,
  `Aww it's so cute when you try to talk about things you don't understand`,
  `I don't know what makes you so stupid but it really works`,
  `You are proof that evolution can go in reverse`,
  `Brains aren't everything. In your case they're nothing`,
  `I thought of you today It reminded me to take the garbage out`,
  `You're so ugly when you look in the mirror your reflection looks away`,
  `I'm sorry I didn't get that - I don't speak idiot`,
  `Quick - check your face! I just found your nose in my business`,
  `It's better to let someone think you're stupid than open your mouth and prove it`,
  `Hey your village called - they want their idiot back`,
  `Were you born this stupid or did you take lessons`,
  `I've been called worse by better`,
  `You're such a beautiful intelligent wonderful person. Oh I'm sorry I thought we were having a lying competition`,
  `I may love to shop but I'm not buying your bull`,
  `I'd slap you but I don't want to make your face look any better`,
  `Calling you an idiot would be an insult to all stupid people`,
  `I just stepped in something that was smarter than you... and smelled better too`,
  `You have the right to remain silent because whatever you say will probably be stupid anyway`,
  `Your so ugly Hello Kitty said goodbye to you`,
  `Could you take a couple steps back. I have a nut allergy`,
  `Your so big a picture of you would fall off the wall`,
  `You look like a before picture`,
];

const express = require('express');
const app = express();
const port = process.env.PORT || 3000;

app.get('/roast', (req, res) => {
  res.send(roasts[Math.floor(Math.random() * roasts.length)]);
});

app.get('/pun', (req, res) => {
  res.send(puns[Math.floor(Math.random() * puns.length)]);
});

app.get('/random', (req, res) => {
  const random = Math.random();
  if (random > 0.85) {
    res.send(roasts[Math.floor(Math.random() * roasts.length)]);
  } else {
    res.send(puns[Math.floor(Math.random() * puns.length)]);
  }
});

app.listen(port, () => {
  console.log(`listening on port ${port}`);
});
